package softpdv.view;

import java.awt.event.KeyEvent;

public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnEstoque = new javax.swing.JButton();
        btnRelatorios = new javax.swing.JButton();
        btnVenda = new javax.swing.JButton();
        btnProduto = new javax.swing.JButton();
        btnValor = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SoftPDV");

        jPanel1.setBackground(new java.awt.Color(151, 0, 222));
        jPanel1.setForeground(new java.awt.Color(255, 199, 0));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 90)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 199, 0));
        jLabel1.setText("SoftPDV");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnEstoque.setBackground(new java.awt.Color(234, 158, 48));
        btnEstoque.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btnEstoque.setForeground(new java.awt.Color(151, 0, 222));
        btnEstoque.setText("Alterar Estoque");
        btnEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstoqueActionPerformed(evt);
            }
        });
        btnEstoque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEstoqueKeyPressed(evt);
            }
        });

        btnRelatorios.setBackground(new java.awt.Color(234, 158, 48));
        btnRelatorios.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btnRelatorios.setForeground(new java.awt.Color(151, 0, 222));
        btnRelatorios.setText("Emitir Relatórios");
        btnRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatoriosActionPerformed(evt);
            }
        });
        btnRelatorios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnRelatoriosKeyPressed(evt);
            }
        });

        btnVenda.setBackground(new java.awt.Color(234, 158, 48));
        btnVenda.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btnVenda.setForeground(new java.awt.Color(151, 0, 222));
        btnVenda.setText("Venda");
        btnVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendaActionPerformed(evt);
            }
        });
        btnVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnVendaKeyPressed(evt);
            }
        });

        btnProduto.setBackground(new java.awt.Color(234, 158, 48));
        btnProduto.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btnProduto.setForeground(new java.awt.Color(151, 0, 222));
        btnProduto.setText("Cadatrar Produto");
        btnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoActionPerformed(evt);
            }
        });
        btnProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnProdutoKeyPressed(evt);
            }
        });

        btnValor.setBackground(new java.awt.Color(234, 158, 48));
        btnValor.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btnValor.setForeground(new java.awt.Color(151, 0, 222));
        btnValor.setText("Alterar Valor");
        btnValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValorActionPerformed(evt);
            }
        });
        btnValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnValorKeyPressed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(255, 199, 0));
        btnSair.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btnSair.setForeground(new java.awt.Color(151, 0, 222));
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        btnSair.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSairKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEstoque, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRelatorios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
                .addGap(214, 214, 214)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                    .addComponent(btnSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(128, 128, 128))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatoriosActionPerformed
        TelaRelatorios telaRelatorios = new TelaRelatorios();
        telaRelatorios.setVisible(true);
    }//GEN-LAST:event_btnRelatoriosActionPerformed

    private void btnEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoqueActionPerformed
        TelaEstoque telaEstoque = new TelaEstoque();
        telaEstoque.setVisible(true);
    }//GEN-LAST:event_btnEstoqueActionPerformed

    private void btnVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendaActionPerformed
        TelaVenda telaVenda = new TelaVenda();
        telaVenda.setVisible(true);
    }//GEN-LAST:event_btnVendaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoActionPerformed
        TelaCadastroProduto telaCadastroProduto = new TelaCadastroProduto();
        telaCadastroProduto.setVisible(true);
    }//GEN-LAST:event_btnProdutoActionPerformed

    private void btnValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValorActionPerformed
        TelaValor telaValor = new TelaValor();
        telaValor.setVisible(true);
    }//GEN-LAST:event_btnValorActionPerformed

    private void btnVendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnVendaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            btnEstoque.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            btnRelatorios.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT){
            btnProduto.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            TelaVenda telaVenda = new TelaVenda();
            telaVenda.setVisible(true);
        }
    }//GEN-LAST:event_btnVendaKeyPressed

    private void btnEstoqueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEstoqueKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            btnRelatorios.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            btnVenda.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT){
            btnValor.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            TelaEstoque telaEstoque = new TelaEstoque();
            telaEstoque.setVisible(true);
        }
    }//GEN-LAST:event_btnEstoqueKeyPressed

    private void btnRelatoriosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnRelatoriosKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            btnVenda.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            btnEstoque.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT){
            btnSair.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            TelaRelatorios telaRelatorios = new TelaRelatorios();
            telaRelatorios.setVisible(true);
        }
    }//GEN-LAST:event_btnRelatoriosKeyPressed

    private void btnProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnProdutoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            btnValor.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            btnSair.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT){
            btnVenda.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            TelaCadastroProduto telaCadastroProduto = new TelaCadastroProduto();
            telaCadastroProduto.setVisible(true);
        }
    }//GEN-LAST:event_btnProdutoKeyPressed

    private void btnSairKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSairKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            btnProduto.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            btnValor.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT){
            btnRelatorios.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            System.exit(0);
        }
    }//GEN-LAST:event_btnSairKeyPressed

    private void btnValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnValorKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            btnSair.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT){
            btnEstoque.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            btnProduto.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            TelaValor telaValor = new TelaValor();
            telaValor.setVisible(true);
        }
    }//GEN-LAST:event_btnValorKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstoque;
    private javax.swing.JButton btnProduto;
    private javax.swing.JButton btnRelatorios;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnValor;
    private javax.swing.JButton btnVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
